/*THIS CODE IS TO CHANGE THE VALUE OF POSITIION'S DIGIT OF THE GIVEN ACTUAL
NUMBER.
 OR WE CAN SAY THAT THIS IS FOR UPDATING VALUE ON A PARTICULAR POSITION
 OF THE GIVER ACTUAL NUMBER*/
//AND IN THIS CODE WE ARE UPDATING THE FIRST POSITION (1 INDEX) TO 1 (0 TO 1);

public class Updatein1 {
    public static void main(String[] args) {
        int Actualno = 5;
        int Bitmask = 1 << 3;
        int Wow = Bitmask | Actualno;
        System.out.println(Wow);
    }
}
// how this code is working -----
/*
 * IN THIS CODE WE TAKE AN ACTUALNO = 5 , THEN DO BITMASK (1<<1) OR LEFT
 * SHIFT OF 1 ,(WE TOOK 1 FOR LEFT SHIFT), SO OUR BINARY NO 0001 BECAME
 * 0010 ( BECAUSE WE DID LEFT SHIFT BY 1 POSITION ), AFTER IT WE DID
 * "OR"(|) OF 0010 WITH GIVEN ACTUALNO =
 * SO THE OUTPUT OF THIS AND OPRATION WAS -----
 * 0010
 * | 0101 (BECAUSE THE BINARY FORM OF 5 IS 0101)
 * = 0111
 * SO EXPECTED OUTPUT WILL WE 0111 WHICH IS 7 IN BINARY FORM .
 * WE CAN CHANGE THE VALUE OF POSITION AND THE ACTUALNO TO PRINT
 * FOR DIFFRENT OUTPUTS.
 */